config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :plans
  devise_for :admins
  devise_for :members
 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_member!

  layout 'system'

  def index; end
end

app/controllers/member_controller.rb
class MembersController < ApplicationController
  layout :application
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_member!
  layout 'system'
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  # before_action :load_relationship, only: [:new, :edit, :update, :create]

  # GET /plans
  def index
    @q = Plan.all.search(params[:q])
    @plans = @q.result(distinct: true).page(params[:page]).per(30)
  end

  # GET /plans/1
  def show; end
  
  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit; end

  # POST /plans
  def create
    @plan = Plan.new(plan_params)

    if @plan.save
      redirect_to @plan, notice: 'Plan foi criado(a) com sucesso!.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /plans/1
  def update
    if @plan.update(plan_params)
      redirect_to @plan, notice: 'Plan foi atualizado(a) com sucesso'
    else
      render action: 'edit'
    end
  end

  # DELETE /plans/1
  def destroy
    @plan.destroy
    redirect_to plans_url, notice: 'Plan foi removido(a) com sucesso.'
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/home/index.html.erb
<%= content_for :title do %>
  Home
<% end %>

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <!-- title right -->
        <h3>Title Left</h3>
      </div>
    </div>

    <div class="title_right">
      <div class="col-md-2 col-sm-2 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <!-- title right -->
          <p>Title Right</p>
        </div>
      </div>
    </div>

    </br>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <!-- Conteudo da página... -->
            <h4>Teste de overdose... </h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_botoes_index.html.erb
<%= link_to(url_for(controller: controller, action: :show, id: object_id),
:class=>"btn btn-default btn-sm", title:"Ver", id: "#{controller}-show") do %>
<i class="fa fa-eye"></i>
<% end %>

<%= link_to(url_for(controller: controller, action: :edit, id: object_id),
:class=>"btn btn-success btn-sm" , title:"Editar", id: "#{controller}-edit") do %>
<i class="fa fa-pencil"></i>
<% end %>

<%= link_to(url_for(controller: controller,action: :destroy, id: object_id), method: :delete, data: { confirm: 'Tem certeza? essa ação não poderá ser desfeita' }, :class=>"btn btn-danger btn-sm no-ajaxify", title:"Apagar", id: "#{controller}-destroy") do %>
<i class="fa fa-trash-o"></i>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag  'application', media: 'all' %>

    <title>Planfinancial</title>

  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared_default/_footer.html.erb
<footer>
  <div class="pull-right">
    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
  </div>
  <div class="clearfix"></div>
</footer>

app/views/layouts/shared_default/_menu.html.erb
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <ul class="nav side-menu">
      <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="index.html">Dashboard</a></li>
          <li><a href="index2.html">Dashboard2</a></li>
          <li><a href="index3.html">Dashboard3</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-edit"></i> Cadastra <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li>
            <%= link_to "Planilhas", new_plan_path %>
          </li>
          <li><a href="form_advanced.html">Advanced Components</a></li>
          <li><a href="form_validation.html">Form Validation</a></li>
          <li><a href="form_wizards.html">Form Wizard</a></li>
          <li><a href="form_upload.html">Form Upload</a></li>
          <li><a href="form_buttons.html">Form Buttons</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/shared_default/_menu_footer.html.erb
<div class="sidebar-footer hidden-small">
  <a data-toggle="tooltip" data-placement="top" title="Settings">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="FullScreen">
    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Lock">
    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
  </a>
</div>

app/views/layouts/shared_default/_top_navigation.html.erb
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <img src="/images/img.jpg" alt="">
            <%= current_member.email %>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Profile</a></li>
            <li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li><a href="javascript:;">Help</a></li>
            <li>
              <%= link_to destroy_member_session_path, method: :delete do %>
                <i class="fa fa-sign-out pull-right"></i> 
                Log Out
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/system.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag  'application', media: 'all' %>

    <title>Planfinancial</title>

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-dollar"></i> <span>PlanFinancial!</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="/images/img.jpg" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>John Doe</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />
            <%= render partial: 'layouts/shared_default/menu' %>
            <%= render partial: 'layouts/shared_default/menu_footer.html.erb'  %>
          </div>
        </div>

        <!-- top navigation -->
          <%= render partial: 'layouts/shared_default/top_navigation' %>

        <!-- page content -->
          <%= yield %>
        <!-- /page content -->

        <!-- footer content -->
          <%= render partial: 'layouts/shared_default/footer' %>
        <!-- /footer content -->
      </div>
    </div>
    <%= javascript_include_tag 'application', media: 'all' %>
  </body>
</html>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/plans/_botoes.html.erb
<div class="btn-group btn-group-sm pull-right hidden-print">
  <%= link_to :back , class: "btn btn-xs btn-default" do %>
    <i class="fa fa-fw fa-arrow-circle-o-left"></i>
    Voltar
  <% end %>

  <% if not defined? lista or lista  %>
    <%= link_to  plans_path, class: "btn  btn-default"  do %>
      <i class="fa fa-fw fa-list-alt"></i>
      Lista
    <% end %>
  <% end %>

  <% if not defined? novo or novo %>
    <%= link_to  new_plan_path, class: "btn  btn-success" do %>
      <i class="fa fa-fw fa-plus"></i>
      Novo
    <% end %>
  <% end %>
</div>

app/views/plans/_form.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%= action_name.titlecase %> Plan</h3>
      </div>

      <div class="title_right">
        <div class="col-md-3 col-sm-3 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <%= yield :botoes %>
          </div>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-offset-3 col-md-6 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <br />
             <%= form_for @plan, html: { class: 'form-horizontal form-label-left' } do |f| %>
                  <% if @plan.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@plan.errors.count, "erro") %> impediu que plan fosse salvo:
                        </h2>
                        <ul>
                          <% @plan.errors.full_messages.each do |msg| %>
                            <li>
                              <%= msg %>
                            </li>
                          <% end %>
                        </ul>
                      </div>
                  <% end %>
    
                                    
                      <div class="form-group">
                                                        <%= f.label :name, class: 'control-label col-md-3 col-sm-3 col-xs-12' %>
                              <div class="col-md-6 col-sm-6 col-xs-12">
                                <%= f.text_field :name, class: 'form-control col-md-7 col-xs-12' %>
                              </div>
                                                </div>
                                    </br>
                  <div class="form-group">
                      <%=  button_tag(type: 'submit', class: "btn btn-primary") do %>
                        <i class="fa fa-check-circle"></i>
                        Salvar
                      <% end %>

                      <%= link_to  plans_path, class: "btn btn-default" do %>
                        <i class="fa fa-times"></i>
                        Cancelar
                      <% end %>
                  </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/plans/edit.html.erb
<%= content_for :title do  %>
	Editar plan
<% end %>

<%= content_for :botoes do %>
  <%= render partial: "botoes" %>
<% end %>

<%= render 'form' %>

app/views/plans/index.html.erb
<%= content_for :title do %>
  Plans
<% end %>

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Plans</h3>
      </div>
    </div>

    <div class="title_right">
      <div class="col-md-2 col-sm-2 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <%= render partial: "botoes", locals: { lista: false } %>
        </div>
      </div>
    </div>

    </br>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-offset-2 col-md-8 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <table id="datatable" class="table table-striped table-bordered">
              <thead>
                <tr>
                                      <th ><%= sort_link @q, :name %></th>
                                    <th class="text-right" width="70%">Ações</th>
                </tr>
              </thead>
              <tbody>
                <% @plans.each do |plan| %>
                  <tr>
                                          <td ><%= plan.name %></td>
                                        <td class="text-right actions">
                      <%= render partial:'layouts/botoes_index', locals: { controller: "plans", object_id: plan.id } %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/plans/new.html.erb
<%= content_for :title do %>
  Cadastro de plan
<% end %>

<%= content_for :botoes do %>
  <%= render partial: "botoes", locals: { novo: false } %>
<% end %>

<%= render 'form' %>

app/views/plans/show.html.erb
  <%= content_for :title do %>
    Detalhes de plan
  <% end %>

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Detalhes da Plan</h3>
      </div>
    </div>

    <div class="title_right">
      <div class="col-md-3 col-sm-3 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <%= render partial: "botoes" %>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-6 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <br />
                            <div class="form-group">
                  <label class="col-md-2 control-label" for="firstname">Name</label>
                  <div class="innerAll half inline-block"><%= @plan.name %></div>
                </div>
                        <div class="separator"></div>
            <div class="form-actions">
              <%= link_to edit_plan_path(@plan), class: "btn btn-default" do %>
                <i class="fa fa-edit"></i>
                Modificar
              <% end %>

              <%= link_to plans_path, class: "btn btn-default" do %>
                <i class="fa fa-arrow-left"></i>
                Voltar
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>